### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by Sharember** [stalary/Source-code-analysis#2]
- 设计模式的例子有的感觉不太恰当，比如策略模式的例子。同时，在介绍各个模式的时候，缺乏一些经验性的总结，比如什么情况下建议使用、好处是什么、坏处是什么，最好可以再加上一点很有代表性的例子，比如 spring 中是怎么使用这种设计模式的。

- spring 源码的解读，个人建议不要从 AppLicationContext 开始往下看，这样容易摸不着头脑。你会对一些步骤感到很奇怪。我觉得在解读源码之前，最好先理清 spring 都做了哪些事；为什么要做；如果是你，你会怎么做；spring 是怎么做的；为什么要这样做。。从下往上看，思路会更清晰一些。通俗一点就是，从 BeanFactory、Resource、ResourceLoader、BeanDefination 这部分开始看起。先看加载过程，然后看初始化过程，最后看整体设计。当然，从上往下看也没问题，但是感觉不是很好，个人建议。

**Comment by stalary** [comment]
好的，最近设计模式这一块我再好好修改一下，Spring的是刚开始看，还没什么头绪，下一步就先看加载过程这一块，谢谢大佬的建议
