### ISSUE TITLE
ArrayList源码分析

### ISSUE THREAD

**Issue by fu1744** [stalary/Source-code-analysis#3]
//构造一个包含特定元素的list,用iterator依次取出collection中的元素
public ArrayList(Collection<? extends E> c) {
    elementData = c.toArray();
    if ((size = elementData.length) != 0) {
        //这里有个bug，c.toArray()可能不会返回Object[]     
    **//这里为什么会不返回Object[]数组，能给解释一下么？ 您指的bug是什么呢？**
        if (elementData.getClass() != Object[].class)
            elementData = Arrays.copyOf(elementData, size, Object[].class);
    } else {
        // replace with empty array.
        this.elementData = EMPTY_ELEMENTDATA;
    }
}

**Comment by fu1744** [comment]
还有就是构造方法传入的Collection不是通过iterator遍历的吧，就是使用了系统的拷贝方法吧？

**Comment by jqs1970291214** [comment]
感谢提出指正。

这里是java官方bug库的，编号 626052，详情请参看https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6260652
出现这个问题的原因我认为主要是toArray()的实现不同。
```java

public <T> T[] toArray();
public Object[] toArray();

```
这个bug已在jdk9得到解决。

第二个问题，非常抱歉这是我的疏忽，这里应该为“按照迭代器返回的顺序排”。稍后就会修正这个问题。

再次感谢!

**Comment by fu1744** [comment]
感谢回答！
