### ISSUE TITLE
设计模式-静态代理-User类

### ISSUE THREAD

**Issue by 1303575952** [stalary/Source-code-analysis#4]
// 使用对象
@Data
@AllArgsConstructor
public class User {

    private Integer id;

    private String username;
}

这里是不是缺了个带参的构造方法。Main中是这样的：
// 测试类
public class Main {

    public static void main(String[] args) {
        ZooProxy proxy = new ZooProxy(new ZooImpl());
        proxy.enter(new User(1, "stalary"));
        proxy.enter(new User(2, "hawk"));
        proxy.enter(new User(3, "claire"));
    }
}
另外还有get/set以及toString()方法，否则与测试结果不符。

**Comment by stalary** [comment]
你好，这里我是用了lombok的注解@AllArgsConstructor，这个相当于全参构造方法，@Data相当于get/set/toString，多谢提醒，我一会补全一下说明
